### ISSUE TITLE
【依頼】フリマアプリ挙動確認	

### ISSUE THREAD

**Issue by ono775** [ono775/furima-28133#10]
## URL
https://furima-28133.herokuapp.com/
## BASIC認証
ID: **meme**
パスワード: **meme123**
## 購入者用のメールアドレスとパスワード
mail: **ono@test.com**
パスワード: **ono123**
## 出品者用のメールアドレスとパスワード
mail: **meme@test.com**
パスワード: **meme123**
## 購入用カード
番号: **4242424242424242**
期限: **3月 2024年**
CVC: **123**

**Comment by apapa1031** [comment]
ご提出ありがとうございます！
確認させて頂きましたが特に問題はないためLGTMとさせて頂きます！

お疲れ様でした！
